src/ServiceApresVenteBundle/Entity/RecFeedCat.php
<?php

namespace ServiceApresVenteBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * RecFeedCat
 *
 * @ORM\Table(name="rec_feed_cat")
 * @ORM\Entity
 */
class RecFeedCat
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id_cat", type="integer",nullable=true)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id_cat;

    /**
     * @var string
     * @Assert\NotBlank()
     * @ORM\Column(name="nom", type="string", length=50, nullable=false)
     */
    private $nom;



    /**
     * @var string
     * @Assert\File(maxSize="500k", mimeTypes={"image/jpeg", "image/jpg", "image/png", "image/GIF"})
     * @ORM\Column(name="image", type="string", length=100, nullable=false)
     */
    private $image;



    /**
     * @return int
     */
    public function getIdCat()
    {
        return $this->id_cat;
    }

    /**
     * @param int $id_cat
     */
    public function setIdCat($id_cat)
    {
        $this->id_cat = $id_cat;
    }

    public function __toString()

    {
        return (string)$this->id_cat;
    }




    /**
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param string $image
     */
    public function setImage($image)
    {
        $this->image = $image;
    }



}

src/ServiceApresVenteBundle/Resources/views/Admin/createCategorie.html.twig
{% block body -%}

    <button class="btn btn-success" data-toggle="modal" data-target="#add_new_record_modal">Ajouter Categorie</button>
    <div class="modal fade" id="add_new_record_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        {{ form_start(form) }}
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span> </button>
                    <h4 class="modal-title" id="myModalLabel">Ajouter Catégorie</h4>
                </div>

                <div class="modal-body">

                    <div class="form-group">
                        <label for="first_name">Nom</label>
                        {{ form_widget(form.nom,{'attr':{'class':'form-control'}} ) }}

                    </div>

                    <div class="form-group">
                        <label for="last_name">Prenom</label>
                        {{ form_widget(form.image,{'attr':{'class':'form-control'}} ) }}
                    </div>



                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    {{ form_row(form.Ajouter,{'attr':{'class':'btn btn-primary'}}) }}
                </div>
            </div>
            {{ form_rest(form) }}
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}

src/ServiceApresVenteBundle/Resources/views/Admin/index.html.twig
{%  extends 'backend/base.html.twig' %}

 {%  block content %}



<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div  class="container-fluid"  >


                <li class="list-inline-item">
                    <h4 class="page-title">Statistique des feedbacks et réclamations</h4>
                </li>





                <div class="row"  style="  display: flex;
  justify-content: center;
  flex-direction: row;">
                    <div class="col-xl-3 col-md-6 " >
                        <div class="card-box widget-user">
                            <div class="text-center">
                                <h2 class="text-pink" data-plugin="counterup">{{ nbRec }}</h2>
                                <h5>Total de Reclamation</h5>

                            </div>
                        </div>
                    </div>

                    <div class="col-xl-3 col-md-6">
                        <div class="card-box widget-user">
                            <div class="text-center">
                                <h2 class="text-warning" data-plugin="counterup">{{nbFeed}}</h2>
                                <h5>Total de Feedback</h5>
                            </div>
                        </div>
                    </div>

                    </center>
                </div sty>
            <div class="col-xl-12 col-md-12">
                <div class="card-box" >
                    <div class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                            <i class="mdi mdi-dots-vertical"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Action</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Another action</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Something else</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Separated link</a>
                        </div>
                    </div>

                    <h4 class="header-title mt-0 m-b-30">Nombre des réclamation aprés Ventes</h4>

                    <div class="widget-box-2">
                        <div class="widget-detail-2">
                            <span class="badge badge-pink badge-pill pull-left m-t-20">{{nbrRecParRapportFeed |number_format }}% <i class="mdi mdi-trending-up"></i> </span>
                            <h2 class="mb-0"> {{ nbrRecParRapportFeed }} </h2>
                            <p class="text-muted m-b-25">Revenue Réclamation par rapport au feedback</p>
                        </div>
                        <div class="progress progress-bar-pink-alt progress-sm mb-0">
                            <div class="progress-bar progress-bar-pink" role="progressbar" aria-valuenow="{{ nbrRecParRapportFeed }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ nbrRecParRapportFeed }}%;">
                                <span class="sr-only">{{nbrRecParRapportFeed  }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-12 col-md-12">
                <div class="card-box">
                    <div class="dropdown pull-right">
                        <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                            <i class="mdi mdi-dots-vertical"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Action</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Another action</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Something else</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Separated link</a>
                        </div>
                    </div>

                    <h4 class="header-title mt-0 m-b-30">Nombre feedback livreur</h4>

                    <div class="widget-box-2">
                        <div class="widget-detail-2">
                            <span class="badge badge-primary badge-pill pull-left m-t-20">{{ nbrFeedParRapportRec |number_format   }}% <i class="mdi mdi-trending-up"></i> </span>
                            <h2 class="mb-0"> {{nbrFeedParRapportRec }} </h2>
                            <p class="text-muted m-b-25">Revenue feedbacks par rapport au réclamation </p>
                        </div>
                        <div class="progress progress-bar-primary-alt progress-sm mb-0">
                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="{{ nbrFeedParRapportRec   }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ nbrFeedParRapportRec   }}%;">
                                <span class="sr-only">{{ nbrFeedParRapportRec   }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
</div>
 {% endblock %}

src/ServiceApresVenteBundle/Resources/views/Admin/readFeedback.html.twig
{%  extends 'backend/base.html.twig' %}


{% block content %}
    <link  href="{{ asset('BundleExterne/css/rating.css') }}" rel="stylesheet">
    <!-- default styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.6/css/star-rating.min.css" media="all" rel="stylesheet" type="text/css" />

    <!-- optionally if you need to use a theme, then include the theme CSS file as mentioned below -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.6/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css" />


    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-xl-4">
                        <a href="#custom-modal" class="btn btn-success btn-md waves-effect waves-light m-b-30" data-animation="fadein" data-plugin="custommodal" data-overlayspeed="200" data-overlaycolor="#36404a"><i class="md md-add"></i> Add Contact</a>
                    </div><!-- end col -->
                </div>
                <!-- end row -->

                <div class="row">
                    {% for entity in feedbacks %}

                    <div class="col-xl-4">
                        <div class="text-center card-box">
                            <div class="dropdown pull-right">
                                <a href="#" class="dropdown-toggle arrow-none card-drop" data-toggle="dropdown" aria-expanded="false">
                                    <i class="mdi mdi-dots-vertical"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <!-- item-->
                                    <a href="" class="dropdown-item">Traiter</a>
                                    <!-- item-->

                                </div>
                            </div>
                            <div>
                                <img src="{{ asset('assets/images/feedbacks/user.png') }}" class="rounded-circle thumb-xl img-thumbnail m-b-10" alt="profile-image">


                                <p class="text-muted font-13"><strong>Note :</strong>

                                    <label for="input-1" class="control-label">{{ entity.note }}</label>



                                    <div class="text-left"><p class="text-muted font-13"><strong>Nom :</strong> <span class="m-l-15">Johnathan Deo</span></p>


                                </div>

                                <button type="button" class="btn btn-custom btn-rounded waves-effect waves-light" data-toggle="modal" data-target="#myModal{{ entity.idFeed }}">Détail</button>
                                <div class="modal fade" id="myModal{{ entity.idFeed }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <br><br><br><br>
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title" id="myModalLabel"> Description de feedback :</h4>

                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row">

                                                    <div class="col-lg-6">

                                                        <ul>
                                                            <p>                                    {{ entity.description }}
                                                            </p>
                                                        </ul>

                                                    </div>
                                                    <div class="col-lg-6">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>

                                            </div>

                                        </div>
                                    </div>
                                </div>


                            </div>

                        </div>

                    </div> <!-- end col -->
                    {% endfor %}

                </div>
                <!-- end row -->


                <!-- end row -->

            </div> <!-- container -->

        </div> <!-- content -->


    </div>


    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="{{ asset('BundleExterne/js/rating.js') }}"></script>

    <!-- important mandatory libraries -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.6/js/star-rating.min.js" type="text/javascript"></script>

    <!-- optionally if you need to use a theme, then include the theme JS file as mentioned below -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.6/themes/krajee-svg/theme.js"></script>

    <!-- optionally if you need translation for your language then include locale file as mentioned below -->
{% endblock %}

src/ServiceApresVenteBundle/Resources/views/Admin/show.html.twig
{% block body -%}
    <h1>Categories</h1>

    <table class="record_properties">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ entity.idCat }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ entity.nom }}</td>
        </tr>
        <tr>
            <th>Prenom</th>
            <td>{{ entity.image }}</td>
        </tr>

        </tbody>
    </table>

    <ul class="record_actions">
        <li>
{#            <a href="{{ path('personne') }}">#}
                Back to the list
            </a>
        </li>
        <li>
{#            <a href="{{ path('personne_edit', { 'id': entity.id }) }}">#}
                Edit
            </a>
        </li>
        <li>/li>
    </ul>
{% endblock %}

src/ServiceApresVenteBundle/Resources/views/Admin/updateCategorie.html.twig
{% block body -%}
    <div class="bd-example">
        <i class="fa fa-pencil-square-o"  style="font-size: 20px; color: #ff8acc;" id="" data-toggle="modal" data-target="#exampleModal{{ entity.idCat }}" ></i>
        <div class="modal fade show" id="exampleModal{{ entity.idCat }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <br><br><br>
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="exampleModalLabel">Modfier Catégorie</h4>

                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        {{ form_start(edit_form) }}
                        <div class="form-group">
                            <label for="recipient-name" class="form-control-label">Nom:</label>
                            {{ form_widget(edit_form.nom,{'attr':{'class':'form-control'}} ) }}
                        </div>
                        <div class="form-group">
                            {{ form_widget(edit_form.image,{'attr':{'class':'form-control'}} ) }}
                        </div>



                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        {{ form_row(edit_form.Ajouter,{'attr':{'class':'btn btn-primary waves-effect waves-light'}}) }}


                    </div>
                    {{ form_rest(edit_form) }}
                    {{ form_end(edit_form) }}

                </div>
            </div>
        </div>
    </div>


{% endblock %}